#!/bin/bash
#
# An SSH_ASKPASS command for MacOS X
#
# Author: Joseph Mocker, Sun Microsystems
# Homepage: http://blog.retep.org/2009/04/09/ssh-askpass-on-osx-10-5/

#
# To use this script:
#     setenv SSH_ASKPASS "macosx-askpass"
#     setenv DISPLAY ":0"
#

TITLE=${MACOSX_ASKPASS_TITLE:-"SSH Passphrase"}

DIALOG="display dialog \"$@\" default answer \"\" with title \"$TITLE\""
DIALOG="$DIALOG with icon caution with hidden answer"

result=`arch -i386 osascript -e 'tell application "Finder"' -e "activate"  -e "$DIALOG" -e 'end tell'`

if [ "$result" = "" ]; then
    exit 1
else
    echo "$result" | sed -e 's/^text returned://' -e 's/, button returned:.*$//'
    exit 0
fi
